version: '3.8'

services:
  iotms-angular:
    image: imdadullah/iotms-angular:latest
    container_name: iotms-angular
    build:
      context: ../../../
      dockerfile: angular/Dockerfile.local
    ports:
      - "4200:80"
    depends_on:
      - iotms-api
    volumes:
      - ./dynamic-env.json://usr/share/nginx/html/dynamic-env.json
    networks:
      - abp-network

  iotms-api:
    image: imdadullah/iotms-api:latest
    container_name: iotms-api
    hostname: iotms-api
    build:
      context: ../../
      dockerfile: src/iotms.HttpApi.Host/Dockerfile.local
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80;
      - Kestrel__Certificates__Default__Path=/root/certificate/localhost.pfx
      - Kestrel__Certificates__Default__Password=76e8b26e-9052-4b40-97e4-06cae03ed5be
      - App__SelfUrl=https://localhost:44354
      - App__AngularUrl=http://localhost:4200
      - App_CorsOrigins=http://localhost:4200
      - App__HealthCheckUrl=http://iotms-api/health-status
      - AuthServer__RequireHttpsMetadata=false
      - AuthServer__Authority=http://iotms-authserver
      - AuthServer__MetaAddress=https://localhost:44334
      - ConnectionStrings__Default=Server=mysql;Port=3306;Userid=root;Password=myPassw0rd;Database=iotms;
      - Redis__Configuration=redis
    ports:
      - "44354:443"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy  
    restart: on-failure    
    volumes:
      - ./certs:/root/certificate
    networks:
      - abp-network
  
  iotms-authserver:
    image: imdadullah/iotms-authserver:latest
    container_name: iotms-authserver
    build:
      context: ../../
      dockerfile: src/iotms.AuthServer/Dockerfile.local
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80;
      - App__SelfUrl=https://localhost:44334
      - App__CorsOrigins=http://localhost:4200,https://localhost:44354
      - AuthServer__RequireHttpsMetadata=false
      - AuthServer__Authority=https://localhost:44334
      - Kestrel__Certificates__Default__Path=/root/certificate/localhost.pfx
      - Kestrel__Certificates__Default__Password=76e8b26e-9052-4b40-97e4-06cae03ed5be
      - ConnectionStrings__Default=Server=mysql;Port=3306;Userid=root;Password=myPassw0rd;Database=iotms;
      - Redis__Configuration=redis
    ports:
      - "44334:443"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: on-failure
    volumes:
      - ./certs:/root/certificate
    networks:
      - abp-network

  db-migrator:
    image: imdadullah/iotms-db-migrator:latest
    container_name: db-migrator
    build:
      context: ../../
      dockerfile: src/iotms.DbMigrator/Dockerfile.local
    environment:
      - OpenIddict__Applications__iotms_App__RootUrl=http://localhost:4200
      - OpenIddict__Applications__iotms_Swagger__RootUrl=https://localhost:44354
      - ConnectionStrings__Default=Server=mysql;Port=3306;Userid=root;Password=myPassw0rd;Database=iotms;
      - Redis__Configuration=redis
    restart: on-failure
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - abp-network    
  
  mysql:
    container_name: mysql-db
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: myPassw0rd
    volumes:
      - mysql_data:/var/lib/mysql
    networks: 
      - abp-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 10s
      timeout: 5s
      retries: 5    
  
  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - abp-network  
    healthcheck:
      test: ["CMD", "redis-cli","ping"]      

volumes:
  mysql_data:
    name: iotms_mysql_data
networks:
  abp-network:
    name: iotms-network
    driver: bridge
