using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace iotms.Accounts
{
    public class AccountManager : AccountManagerBase
    {
        //<suite-custom-code-autogenerated>
        public AccountManager(IAccountRepository accountRepository)
            : base(accountRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}