using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace iotms.Accounts
{
    public class Account : AccountBase
    {
        //<suite-custom-code-autogenerated>
        protected Account()
        {

        }

        public Account(Guid id, int rooms, bool status, string? name = null, string? location = null, string? address = null, string? contact = null, string? email = null, string? web = null)
            : base(id, rooms, status, name, location, address, contact, email, web)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}