using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using iotms.Permissions;
using iotms.Accounts;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using iotms.Shared;

namespace iotms.Accounts
{
    public class AccountsAppService : AccountsAppServiceBase, IAccountsAppService
    {
        //<suite-custom-code-autogenerated>
        public AccountsAppService(IAccountRepository accountRepository, AccountManager accountManager, IDistributedCache<AccountDownloadTokenCacheItem, string> downloadTokenCache)
            : base(accountRepository, accountManager, downloadTokenCache)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}