using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace iotms.Devices
{
    public class DeviceManager : DeviceManagerBase
    {
        //<suite-custom-code-autogenerated>
        public DeviceManager(IDeviceRepository deviceRepository)
            : base(deviceRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}